In [3]:
import numpy as np

In [5]:
list=[1,2,3]
print(type(list))
array=np.array(list)
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [10]:
matrix_1 = [[1,2,3],[6,7,8]]
matrix_1

np.array(matrix_1)


array([[1, 2, 3],
       [6, 7, 8]])

In [12]:
matrix_2= np.arange(5,50,5).reshape(3,3)
print(matrix_2)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [19]:
random=np.random.randint(0,100,15)
print(random)
random.max()

[29 13 76 60 93 61 21 15 28 22 30 87 57 46 81]


93

In [26]:
arr=np.arange(0,20,1).reshape(5,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [30]:
arr.shape



dtype('int32')